### ISSUE TITLE
BaseLogger is not exported from @dbbs/next-cache-handler-core

### ISSUE THREAD

**Issue by ForeshadowRU** [DBB-Software/next-cache-handler#58]
Hello. I have problems accessing BaseLogger class.

I'm using:
```txt
        "@dbbs/next-cache-handler-core": "^1.1.1",
        "@dbbs/next-cache-handler-redis": "^1.0.5",
   ```
![image](https://github.com/user-attachments/assets/11830c91-9941-4b05-8b65-e106ac81b0fb)

**Comment by RomanBobrovskiy** [comment]
Hi, @ForeshadowRU , yes this is how linking between "internal" and "external" packages works under turbo repo. We will check the fix to include all necessary types into the package output

**Comment by RomanBobrovskiy** [comment]
should be fixed here: https://github.com/DBB-Software/next-cache-handler/pull/60

**Comment by RomanBobrovskiy** [comment]
please update your package to v1.2.0, that should be fixed here
